fixed yaml

diff --git a/azure-pipelines-prod.yml b/azure-pipelines-prod.yml
--- a/azure-pipelines-prod.yml
+++ b/azure-pipelines-prod.yml
@@ -21,41 +21,42 @@ stages:
     displayName: 'Validate Terraform'
     jobs:
       - job: validate_tf
-        - task: AzureCLI@2
-          displayName: Pre flight
-          inputs:
-            azureSubscription: $(serviceConnection)
-            scriptLocation: inlineScript
-            scriptType: bash
-            inlineScript: |
-              set -eu  # fail on error
-              # Terraform allow auth via Azure CLI only with user, but not with Service Principle. Thus, this mess
-        - task: AzureCLI@2 #we need to be loged in to AZ, so we use AzureCLI@2 instead of bash, for backend connection
-          displayName: tf init
-          inputs:
-            azureSubscription: $(serviceConnection)
-            scriptLocation: inlineScript
-            scriptType: bash
-            inlineScript: |
-              set -eu  # fail on error
-              export ARM_USE_MSI=true
-              export ARM_SUBSCRIPTION_ID=$(iac_subscription)
-              export ARM_TENANT_ID=$(tenant_id)
-              export ARM_CLIENT_ID=$(client_id)
-              terraform init \
-              -input=false \
-              -backend-config=storage_account_name=$(bk-str-account-name) \
-              -backend-config=container_name=$(bk-container-name) \
-              -backend-config=key=$(Build.Repository.Name).tfstate \
-              -backend-config=resource_group_name=$(bk-rg-name) \
-              -backend-config=use_azuread_auth=true
-        - task: AzureCLI@2
-          displayName: tf plan
-          inputs:
-            azureSubscription: $(serviceConnection)
-            scriptType: bash
-            scriptLocation: inlineScript
-            inlineScript: |
-              set -eu  # fail on error
-              terraform plan \
-              -input=false -out=tf_plan.out
+        steps:
+          - task: AzureCLI@2
+            displayName: Pre flight
+            inputs:
+              azureSubscription: $(serviceConnection)
+              scriptLocation: inlineScript
+              scriptType: bash
+              inlineScript: |
+                set -eu  # fail on error
+                # Terraform allow auth via Azure CLI only with user, but not with Service Principle. Thus, this mess
+          - task: AzureCLI@2 #we need to be loged in to AZ, so we use AzureCLI@2 instead of bash, for backend connection
+            displayName: tf init
+            inputs:
+              azureSubscription: $(serviceConnection)
+              scriptLocation: inlineScript
+              scriptType: bash
+              inlineScript: |
+                set -eu  # fail on error
+                export ARM_USE_MSI=true
+                export ARM_SUBSCRIPTION_ID=$(iac_subscription)
+                export ARM_TENANT_ID=$(tenant_id)
+                export ARM_CLIENT_ID=$(client_id)
+                terraform init \
+                -input=false \
+                -backend-config=storage_account_name=$(bk-str-account-name) \
+                -backend-config=container_name=$(bk-container-name) \
+                -backend-config=key=$(Build.Repository.Name).tfstate \
+                -backend-config=resource_group_name=$(bk-rg-name) \
+                -backend-config=use_azuread_auth=true
+          - task: AzureCLI@2
+            displayName: tf plan
+            inputs:
+              azureSubscription: $(serviceConnection)
+              scriptType: bash
+              scriptLocation: inlineScript
+              inlineScript: |
+                set -eu  # fail on error
+                terraform plan \
+                -input=false -out=tf_plan.out
